// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2flMFM1bETpYyoc0tp0JhxqBKQUkcjAk',
    appId: '1:976213551876:web:dece8c23e6a097f268fe51',
    messagingSenderId: '976213551876',
    projectId: 'heros-barber',
    authDomain: 'heros-barber.firebaseapp.com',
    storageBucket: 'heros-barber.firebasestorage.app',
    measurementId: 'G-5YPCS23X2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJWXtEdNvCCTflBGy41f6LvrhsMiD38v4',
    appId: '1:976213551876:android:c09f0d2a51c8450e68fe51',
    messagingSenderId: '976213551876',
    projectId: 'heros-barber',
    storageBucket: 'heros-barber.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRag96V8945pGpwY3-zYiscMvjwl0MTJs',
    appId: '1:976213551876:ios:cfd0f7a5f981755f68fe51',
    messagingSenderId: '976213551876',
    projectId: 'heros-barber',
    storageBucket: 'heros-barber.firebasestorage.app',
    iosBundleId: 'com.example.herosb',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRag96V8945pGpwY3-zYiscMvjwl0MTJs',
    appId: '1:976213551876:ios:cfd0f7a5f981755f68fe51',
    messagingSenderId: '976213551876',
    projectId: 'heros-barber',
    storageBucket: 'heros-barber.firebasestorage.app',
    iosBundleId: 'com.example.herosb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2flMFM1bETpYyoc0tp0JhxqBKQUkcjAk',
    appId: '1:976213551876:web:adc595ee173e592168fe51',
    messagingSenderId: '976213551876',
    projectId: 'heros-barber',
    authDomain: 'heros-barber.firebaseapp.com',
    storageBucket: 'heros-barber.firebasestorage.app',
    measurementId: 'G-3BX24905DN',
  );
}

